apiVersion: v1
kind: Service
metadata:
  name: laravel-kubernetes-demo
spec:
  type: NodePort
  selector:
    app: laravel-kubernetes-demo
  ports:
    - name: laravel-http
      protocol: TCP
      port: 80
      targetPort: 80