apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: laravel-kubernetes-demo 
spec:
  selector:
    matchLabels:
      app: laravel-kubernetes-demo
  replicas: 2 # tells deployment to run 2 pod matching the template
  strategy:
   rollingUpdate:
     maxSurge: 0         # <2>
     maxUnavailable: 1   # <3>
   type: RollingUpdate   # <1>
  template:
    metadata:
      labels:
        app: laravel-kubernetes-demo
    spec:
      containers:
      - name: laravel-kubernetes-demo
        image: skeletondocker/laravel-kubernetes-demo:latest
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 2  
        envFrom:
        - configMapRef:
            name: laravel-app-backend
        env:
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80