apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-kubernetes-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-kubernetes-demo
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50